// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ticker-variants/BlackGoldChrome.tsx": () => import("../components/mockups/ticker-variants/BlackGoldChrome.tsx"),
  "./components/mockups/ticker-variants/DarkChrome.tsx": () => import("../components/mockups/ticker-variants/DarkChrome.tsx"),
  "./components/mockups/ticker-variants/FullColor.tsx": () => import("../components/mockups/ticker-variants/FullColor.tsx"),
  "./components/mockups/ticker-variants/GoldChrome.tsx": () => import("../components/mockups/ticker-variants/GoldChrome.tsx"),
  "./components/mockups/ticker-variants/Picker.tsx": () => import("../components/mockups/ticker-variants/Picker.tsx")
};
